/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MIMX9596xxxxN
package_id: MIMX9596AVZXN
mcu_data: ksdk2_0
processor_version: 16.1.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm7}
- pin_list:
  - {pin_num: P44, peripheral: LPUART3, signal: lpuart_rx, pin_signal: GPIO_IO15, PD: ENABLED, FSEL1: SLIGHTLY_FAST_SLEW_RATE, DSE: X4}
  - {pin_num: N51, peripheral: LPUART3, signal: lpuart_tx, pin_signal: GPIO_IO14, PD: ENABLED, FSEL1: SLIGHTLY_FAST_SLEW_RATE}
  - {pin_num: AJ41, peripheral: FLEXSPI1, signal: 'flexspi_a_ss_b, 0', pin_signal: XSPI1_SS0_B, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AJ43, peripheral: FLEXSPI1, signal: flexspi_a_sclk, pin_signal: XSPI1_SCLK, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AH42, peripheral: FLEXSPI1, signal: 'flexspi_a_ss_b, 1', pin_signal: XSPI1_SS1_B, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AJ45, peripheral: FLEXSPI1, signal: 'flexspi_a_data_bit, 0', pin_signal: XSPI1_DATA0, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AK44, peripheral: FLEXSPI1, signal: flexspi_a_dqs, pin_signal: XSPI1_DQS, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AJ47, peripheral: FLEXSPI1, signal: 'flexspi_a_data_bit, 2', pin_signal: XSPI1_DATA2, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AH46, peripheral: FLEXSPI1, signal: 'flexspi_a_data_bit, 1', pin_signal: XSPI1_DATA1, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AJ49, peripheral: FLEXSPI1, signal: 'flexspi_a_data_bit, 4', pin_signal: XSPI1_DATA4, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AK48, peripheral: FLEXSPI1, signal: 'flexspi_a_data_bit, 3', pin_signal: XSPI1_DATA3, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AJ51, peripheral: FLEXSPI1, signal: 'flexspi_a_data_bit, 6', pin_signal: XSPI1_DATA6, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AK50, peripheral: FLEXSPI1, signal: 'flexspi_a_data_bit, 5', pin_signal: XSPI1_DATA5, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
  - {pin_num: AH50, peripheral: FLEXSPI1, signal: 'flexspi_a_data_bit, 7', pin_signal: XSPI1_DATA7, PD: DISABLED, FSEL1: SlOW_SLEW_RATE, DSE: X6}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-M7F[cm7] */
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO14__LPUART3_TX, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO14__LPUART3_TX, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_FSEL1(2U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_PD_MASK);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO15__LPUART3_RX, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO15__LPUART3_RX, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_FSEL1(2U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_PD_MASK);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA0__FLEXSPI1_A_DATA_BIT0, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA0__FLEXSPI1_A_DATA_BIT0, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA1__FLEXSPI1_A_DATA_BIT1, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA1__FLEXSPI1_A_DATA_BIT1, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA2__FLEXSPI1_A_DATA_BIT2, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA2__FLEXSPI1_A_DATA_BIT2, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA3__FLEXSPI1_A_DATA_BIT3, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA3__FLEXSPI1_A_DATA_BIT3, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA4__FLEXSPI1_A_DATA_BIT4, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA4__FLEXSPI1_A_DATA_BIT4, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA5__FLEXSPI1_A_DATA_BIT5, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA5__FLEXSPI1_A_DATA_BIT5, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA6__FLEXSPI1_A_DATA_BIT6, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA6__FLEXSPI1_A_DATA_BIT6, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA7__FLEXSPI1_A_DATA_BIT7, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DATA7__FLEXSPI1_A_DATA_BIT7, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DQS__FLEXSPI1_A_DQS, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_DQS__FLEXSPI1_A_DQS, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_SCLK__FLEXSPI1_A_SCLK, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_SCLK__FLEXSPI1_A_SCLK, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_SS0_B__FLEXSPI1_A_SS0_B, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_SS0_B__FLEXSPI1_A_SS0_B, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_SS1_B__FLEXSPI1_A_SS1_B, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_XSPI1_SS1_B__FLEXSPI1_A_SS1_B, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(63U));
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
